#!/usr/bin/env python3
"""
agent_inference.py — On-demand Traffic Forecast & Factor Attribution Engine
============================================================================

Loads pre-trained CatBoost models and the pre-built feature grid (Parquet)
to generate hourly traffic forecasts with per-row factor attribution.

Designed for two usage modes:
  1. CLI:   python agent_inference.py --start 2027-01-01 --end 2029-12-31
  2. Import: from agent_inference import TrafficPredictor
               p = TrafficPredictor()
               df = p.predict_and_explain("2028-07-04", "2028-07-04")

The notebook (model_notebook.ipynb) handles 2026 pre-generation.
This script handles 2027–2029 on-demand / Agent-driven queries.

Requirements:
  - Trained .cbm models in ../models/{kfz_h,sv_h,v_kfz}/
  - Pre-built feature grid: ../processed/future_grid_2027_2029.parquet
    (generated by the notebook Cell 50 after full retrain)
  - catboost, pandas, numpy, pyarrow
"""

import argparse
import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from catboost import CatBoostRegressor

warnings.filterwarnings("ignore")

# =============================================================================
# 0. Path Resolution — find repo root relative to this script
# =============================================================================
ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data_autobahn"
PROC_DIR = ROOT / "processed"
MODEL_DIR = ROOT / "models"

# =============================================================================
# 1. Feature Definitions (MUST match model_notebook.ipynb §3.5 exactly)
# =============================================================================
CALENDAR = [
    "hour", "weekday", "month", "doy", "week_of_year",
    "is_weekend", "is_friday", "is_saturday", "is_sunday",
    "hour_sin", "hour_cos", "dow_sin", "dow_cos",
    "month_sin", "month_cos", "doy_sin", "doy_cos",
]
STATIC_NUM = ["bab_km", "longitude", "latitude"]
STATIC_CAT = ["site_id", "road", "direction", "site_name", "tagestyp", "season"]

HOLIDAY = [
    "is_school_holiday_DE_BY", "is_school_holiday_AT_SB", "is_school_holiday_AT_TI",
    "is_public_holiday_DE_BY", "is_public_holiday_AT_SB", "is_public_holiday_AT_TI",
    "school_holiday_count", "public_holiday_count",
    "is_holiday_start", "is_holiday_end", "in_traffic_window",
    "days_to_holiday_start", "days_since_holiday_end", "total_holiday_overlap",
    "is_departure_wave_day", "is_return_wave_day",
]
HOLIDAY_CAT = ["window_direction", "window_risk_level", "a8_direction", "a93_direction"]
WEATHER = ["w_precip", "w_snow", "w_lowvis", "w_tmin", "w_tmax", "w_ice"]
WEATHER_CAT = ["weather_source"]
TEMP = ["lt_mean", "fbt_mean", "fbt_min"]
CONSTRUCTION = [
    "has_a8_construction", "has_a93_construction", "a8_construction_count", "a93_construction_count",
    "has_2_plus_0", "two_plus_0_count", "max_closed_lanes", "sum_closed_lanes", "has_target_bbox_construction",
]
EVENTS = [
    "has_special_event", "active_event_count", "max_impact_level", "impact_score",
    "affects_a8_ost", "affects_a93_sued",
    "has_munich_event", "has_salzburg_event", "has_rosenheim_event", "has_kufstein_event",
    "has_confirmed_event", "has_estimated_event",
]

PROF_KFZ = ["prof_kfz_shd", "prof_kfz_sht", "prof_kfz_shm", "prof_kfz_p90", "prof_kfz_shs"]
PROF_LKW = ["prof_lkw_shd", "prof_lkw_sht"]
PROF_V = ["prof_v_shd", "prof_v_p85", "prof_v_sht"]

COND = HOLIDAY + HOLIDAY_CAT + WEATHER + WEATHER_CAT + TEMP + CONSTRUCTION + EVENTS
CAT_FEATURES = STATIC_CAT + HOLIDAY_CAT + WEATHER_CAT

FEATURES_KFZ = CALENDAR + STATIC_NUM + STATIC_CAT + PROF_KFZ + COND
FEATURES_LKW = CALENDAR + STATIC_NUM + STATIC_CAT + PROF_KFZ + PROF_LKW + COND
FEATURES_SPD = CALENDAR + STATIC_NUM + STATIC_CAT + PROF_KFZ + PROF_V + COND + ["kfz_p50_pred"]

# Factor attribution groups (matches notebook §3.5)
EXPLANATION_GROUPS = {
    "Station & Location":       ["site_id", "road", "direction", "site_name"] + STATIC_NUM,
    "Historical Patterns":      PROF_KFZ,
    "Calendar & Season":        CALENDAR + ["season"],
    "Holiday Effect":           HOLIDAY + HOLIDAY_CAT + ["tagestyp"],
    "Weather & Road":           WEATHER + WEATHER_CAT + TEMP,
    "Special Events":           EVENTS,
    "Construction":             CONSTRUCTION,
}

FACTOR_DISPLAY = {
    "Station & Location":       "Road Segment and Detector Attributes",
    "Historical Patterns":      "Historical Traffic Baseline",
    "Calendar & Season":        "Date and Time Pattern",
    "Holiday Effect":           "Holiday Effect",
    "Weather & Road":           "Weather and Temperature",
    "Special Events":           "Special Events",
    "Construction":             "Construction Impact",
}

# =============================================================================
# 2. Constants (matches notebook §1.1)
# =============================================================================
KFZ_CLIP_MIN = 0.0
LKW_RATIO_CLIP_MIN = 0.0
SPEED_CLIP_MIN = 20.0
SPEED_CLIP_MAX = 160.0
CONFORMAL_Q = 23.3  # Hardcoded from 2025 held-out calibration (notebook §5)


# =============================================================================
# 3. TrafficPredictor — main class
# =============================================================================
class TrafficPredictor:
    """Loads models + feature grid, exposes predict_and_explain() for on-demand use."""

    def __init__(self, grid_path: Path | None = None):
        """
        Parameters
        ----------
        grid_path : Path | None
            Path to the pre-built feature grid Parquet.
            Defaults to PROC_DIR / "future_grid_2026_2029.parquet"
            (which covers all of 2026–2029).
        """
        print("Loading CatBoost models...")
        self.kfz_model = CatBoostRegressor()
        self.kfz_model.load_model(str(MODEL_DIR / "kfz_h" / "multi.cbm"))
        self.lkw_model = CatBoostRegressor()
        self.lkw_model.load_model(str(MODEL_DIR / "sv_h" / "lkw_ratio.cbm"))
        self.spd_model = CatBoostRegressor()
        self.spd_model.load_model(str(MODEL_DIR / "v_kfz" / "speed_drop.cbm"))
        print("  ✓ kfz_h (MultiQuantile)  |  sv_h (lkw_ratio)  |  v_kfz (speed_drop)")

        # Load feature grid
        _grid_path = grid_path or (PROC_DIR / "future_grid_2026_2029.parquet")
        if not _grid_path.exists():
            # Fallback: try 2027-2029 split grid
            _alt = PROC_DIR / "future_grid_2027_2029.parquet"
            if _alt.exists():
                _grid_path = _alt
            else:
                raise FileNotFoundError(
                    f"Feature grid not found at {_grid_path} or {_alt}. "
                    "Run model_notebook.ipynb Cell 49–50 first to generate the grid."
                )
        print(f"Loading feature grid: {_grid_path.name}...")
        self.base_grid = pd.read_parquet(_grid_path)
        self.base_grid["date"] = pd.to_datetime(self.base_grid["date"])
        print(f"  ✓ {len(self.base_grid):,} rows loaded")

        # Cache cat feature indices for fast type conversion
        self._cat_cols_kfz = [c for c in CAT_FEATURES if c in FEATURES_KFZ]
        self._cat_cols_lkw = [c for c in CAT_FEATURES if c in FEATURES_LKW]
        self._cat_cols_spd = [c for c in CAT_FEATURES if c in FEATURES_SPD]

    # ------------------------------------------------------------------
    def predict_and_explain(self, start_date: str, end_date: str) -> pd.DataFrame:
        """Generate hourly forecast + factor attribution for a date range.

        Parameters
        ----------
        start_date, end_date : str
            ISO-format dates, e.g. "2027-01-01", "2027-12-31".

        Returns
        -------
        pd.DataFrame with columns:
            site_id, road, direction, site_name, date, hour,
            kfz_h_p10, kfz_h_p50, kfz_h_p90, sv_h_pred, v_kfz_pred,
            interval_width, relative_interval_width, reason
        """
        mask = (self.base_grid["date"] >= pd.Timestamp(start_date)) & \
               (self.base_grid["date"] <= pd.Timestamp(end_date))
        df = self.base_grid[mask].copy()
        if df.empty:
            raise ValueError(f"No data in feature grid for {start_date} → {end_date}")

        print(f"Inference: {len(df):,} rows  ({start_date} → {end_date})")

        # --- 1. kfz_h prediction (MultiQuantile: P10/P50/P90) ---
        X_kfz = df[FEATURES_KFZ].copy()
        for c in self._cat_cols_kfz:
            X_kfz[c] = X_kfz[c].astype(str)
        kfz_preds = self.kfz_model.predict(X_kfz)  # shape (N, 3)

        # Apply conformal calibration
        df["kfz_h_p10"] = np.clip(kfz_preds[:, 0] - CONFORMAL_Q, KFZ_CLIP_MIN, None)
        df["kfz_h_p50"] = np.clip(kfz_preds[:, 1], KFZ_CLIP_MIN, None)
        df["kfz_h_p90"] = kfz_preds[:, 2] + CONFORMAL_Q

        # Monotonicity constraint: P90 ≥ P50 ≥ P10
        df["kfz_h_p50"] = np.maximum(df["kfz_h_p10"], df["kfz_h_p50"])
        df["kfz_h_p90"] = np.maximum(df["kfz_h_p50"], df["kfz_h_p90"])

        # --- 2. sv_h prediction (lkw_ratio × kfz_p50) ---
        X_lkw = df[FEATURES_LKW].copy()
        for c in self._cat_cols_lkw:
            X_lkw[c] = X_lkw[c].astype(str)
        lkw_ratio = np.clip(self.lkw_model.predict(X_lkw), LKW_RATIO_CLIP_MIN, None)
        df["sv_h_pred"] = lkw_ratio * df["kfz_h_p50"]

        # --- 3. v_kfz prediction (prof_v_p85 − speed_drop, with G3 flow input) ---
        df["kfz_p50_pred"] = df["kfz_h_p50"].values
        X_spd = df[FEATURES_SPD].copy()
        for c in self._cat_cols_spd:
            X_spd[c] = X_spd[c].astype(str)
        speed_drop = self.spd_model.predict(X_spd)
        df["v_kfz_pred"] = np.clip(
            df["prof_v_p85"].to_numpy() - speed_drop, SPEED_CLIP_MIN, SPEED_CLIP_MAX
        )

        # --- 4. Interval & confidence metrics ---
        df["interval_width"] = df["kfz_h_p90"] - df["kfz_h_p10"]
        df["relative_interval_width"] = df["interval_width"] / (df["kfz_h_p50"] + 1.0)

        # --- 5. Hourly factor attribution (feature-group ablation) ---
        # Same algorithm as notebook Cell 48, with Bug 1 fix (temperature → 10.0).
        print("Computing hourly factor attribution (feature-group ablation)...")
        group_names = list(EXPLANATION_GROUPS.keys())
        display_names = [FACTOR_DISPLAY[g] for g in group_names]
        cats_set = set(self._cat_cols_kfz)
        temp_cols = {"lt_mean", "fbt_mean", "fbt_min"}

        n = len(df)
        contribs = np.empty((n, len(group_names)), dtype=np.float64)

        # Full prediction (already computed → kfz_h_p50 before conformal)
        # Recompute clean P50 for ablation baseline (without conformal shift)
        full_p50 = np.clip(kfz_preds[:, 1], KFZ_CLIP_MIN, None)

        for gi, gname in enumerate(group_names):
            gfeats = EXPLANATION_GROUPS[gname]
            X_abl = X_kfz.copy()
            for c in gfeats:
                if c not in X_abl.columns:
                    continue
                if c in cats_set:
                    X_abl[c] = "__NEUTRAL__"
                elif c in temp_cols:
                    X_abl[c] = 10.0  # ★ Bug 1 fix: neutral temperature, not 0°C
                else:
                    X_abl[c] = 0.0
            abl_p50 = np.clip(self.kfz_model.predict(X_abl)[:, 1], KFZ_CLIP_MIN, None)
            contribs[:, gi] = np.abs(full_p50 - abl_p50)

        # Normalize to percentages
        tot = contribs.sum(axis=1, keepdims=True)
        tot[tot < 1e-9] = 1.0
        pct = contribs / tot * 100.0

        # Build reason strings
        reasons = []
        for row in pct:
            order = np.argsort(row)[::-1]
            parts = [f"{display_names[j]}: {row[j]:.1f}%" for j in order if row[j] >= 1.0]
            reasons.append("；".join(parts))
        df["reason"] = reasons

        # --- 6. Format output ---
        out_cols = [
            "site_id", "road", "direction", "site_name", "date", "hour",
            "kfz_h_p10", "kfz_h_p50", "kfz_h_p90", "sv_h_pred", "v_kfz_pred",
            "interval_width", "relative_interval_width", "reason",
        ]
        result = df[out_cols].copy()

        # Type formatting (matches notebook Cell 50 output)
        for col in ["kfz_h_p10", "kfz_h_p50", "kfz_h_p90", "sv_h_pred", "interval_width"]:
            result[col] = result[col].round(0).astype(int)
        result["v_kfz_pred"] = result["v_kfz_pred"].round(1)
        result["relative_interval_width"] = result["relative_interval_width"].round(4)
        result["date"] = result["date"].dt.strftime("%Y-%m-%d")

        return result


# =============================================================================
# 4. CLI Interface
# =============================================================================
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate hourly traffic forecast with factor attribution"
    )
    parser.add_argument(
        "--start", type=str, required=True,
        help="Start date (YYYY-MM-DD), e.g. 2027-01-01"
    )
    parser.add_argument(
        "--end", type=str, required=True,
        help="End date (YYYY-MM-DD), e.g. 2029-12-31"
    )
    parser.add_argument(
        "--out", type=str, default=None,
        help="Output CSV filename (saved to data_autobahn/). Default: forecast_<start>_<end>_hourly.csv"
    )
    parser.add_argument(
        "--grid", type=str, default=None,
        help="Path to feature grid parquet (default: processed/future_grid_2026_2029.parquet)"
    )
    args = parser.parse_args()

    # Determine output path
    if args.out:
        out_path = DATA_DIR / args.out
    else:
        out_path = DATA_DIR / f"forecast_{args.start}_{args.end}_hourly.csv"

    # Resolve grid path
    grid_path = Path(args.grid) if args.grid else None

    # Run
    predictor = TrafficPredictor(grid_path=grid_path)
    result = predictor.predict_and_explain(args.start, args.end)

    result.to_csv(out_path, index=False)
    size_mb = out_path.stat().st_size / 1e6
    print(f"✓ Generated {len(result):,} rows ({size_mb:.1f} MB) → {out_path}")
    print(f"  Columns: {list(result.columns)}")
    print(f"  Example reason: {result['reason'].iloc[0]}")
